packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@sentry/cli": true
  core-js: false
  esbuild: true

minimumReleaseAgeExclude:
  - pg-cloudflare@1.4.1
  - pg-connection-string@2.14.1
  - pg-protocol@1.16.1
  - pg@8.23.1
  - "@aws-sdk/client-s3@3.1144.0"
  - "@aws-sdk/s3-request-presigner@3.1144.0"
